# Generated by Django 6.1.1 on 2026-09-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sourcecodelink', models.URLField(blank=True)),
                ('projectlink', models.URLField(blank=True)),
                ('morelink', models.URLField(blank=True)),
            ],
        ),
    ]
