# Generated by Django 6.1.1 on 2026-09-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
