# Generated by Django 6.1.1 on 2026-09-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
