# Generated by Django 6.1.1 on 2026-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('value1', models.CharField(max_length=30)),
                ('label1', models.CharField(max_length=30)),
                ('value2', models.CharField(max_length=30)),
                ('label2', models.CharField(max_length=30)),
                ('value3', models.CharField(max_length=30)),
                ('label3', models.CharField(max_length=30)),
            ],
        ),
    ]
