# Generated by Django 6.1.1 on 2026-09-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementcard',
            old_name='name',
            new_name='title',
        ),
    ]
