# Generated by Django 6.1.1 on 2026-09-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
