# Generated by Django 6.1.1 on 2026-09-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_rename_ip_adress_visitor_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
