# Generated by Django 6.1.1 on 2026-09-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('start', models.DateField(blank=True)),
                ('end', models.DateField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='externalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='externalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
