# Generated by Django 6.1.1 on 2026-09-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalexpense',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='externalincome',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='externalincome',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
