# Generated by Django 6.1.1 on 2026-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearsExperience', models.PositiveIntegerField(max_length=2)),
                ('projectsCompleted', models.PositiveIntegerField(max_length=2)),
            ],
        ),
    ]
