# Generated by Django 6.1.1 on 2026-09-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestatic',
            name='projectsCompleted',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='homestatic',
            name='yearsExperience',
            field=models.PositiveIntegerField(),
        ),
    ]
